server:
  port: 7000
spring:
  zipkin:
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做服务名
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product_route # 当前路由的标识, 要求唯一
#          uri: http://localhost:8081 # 请求要转发到的地址
          uri: lb://service-product # 请求要转发到的地址
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/product-serve/** # 当请求路径满足Path指定的规则时,才进行路由转发
            - Before=2023-11-28T00:00:00.000+08:00 #限制请求时间在2019-11-28之前
            - Method=GET #限制请求方式为POST
            - Age=18,60
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
            - SetStatus=250
            - Log=true,false
        - id: order_route # 当前路由的标识, 要求唯一
          uri: lb://service-order # 请求要转发到的地址
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/order-serve/** # 当请求路径满足Path指定的规则时,才进行路由转发
            - Before=2023-11-28T00:00:00.000+08:00 #限制请求时间在2019-11-28之前
            - Method=GET #限制请求方式为POST
            - Age=18,60
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
            - SetStatus=250
            - Log=true,false
