server:
  port: 8081
spring:
  zipkin:
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做服务名
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.2.120:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
config:
  appName: product1
  env: dev
dubbo:
  scan:
    base-packages: com.chow.service.impl # 开启包扫描
  protocols:
    dubbo:
      name: dubbo # 服务协议
      port: -1 # 服务端口
  registry:
    address: spring-cloud://localhost # 注册中心